icondir = join_paths(get_option('datadir'), 'icons/hicolor')
install_data(
  'arabicon.png',
  rename: 'io.github.Arabicon.png',
  install_dir: join_paths(icondir, '48x48/apps')
)
install_data(
  'arabicon.svg',
  rename: 'io.github.Arabicon.svg',
  install_dir: join_paths(icondir, 'scalable/apps')
)
